### ISSUE TITLE
Offer an alternative full-screen alarm display for tactile operation

### ISSUE THREAD

**Issue by ltguillaume** [BlackyHawky/Clock#134]
**Is your feature request related to a problem? Please describe.**

I've always liked the idea of an alarm display that allows you to dismiss it easily when you're not looking at your phone or when it is still in your pocket. The current display (with or without the slide option) isn't working for that.

**Describe the solution you'd like**

I like the way Simple Alarm Clock has implemented this:

![image](https://github.com/user-attachments/assets/31422da8-03df-4f6c-bd31-917d55b409a4)
You have to long-press any of the two big buttons to either snooze or dismiss it, which is perfectly possible without taking the phone out of your pocket.

**Use case**

This really makes it much easier to quickly dismiss an alarm, so you don't have to annoy the people around you with your alarms for too long 😛

It also allows for "tactile operation" by just determining the edges of your phone, which allows you to keep your eyes on the road, another screen or a conversation partner.

**Additional context**

This design probably also requires the app to ignore the proximity sensor, so that the display turns on and stays on while the phone's in your pocket.

**Comment by BlackyHawky** [comment]
I don't plan to modify this interface except as requested in #95.
Indeed, I want to stay close to what the Google application offers from which this application is derived.

Finally, although this is just a personal opinion, the proposed interface is rather ugly compared to the current interface 😅

> …which allows you to keep your eyes on the road…

I hope you don't use your phone while driving 😉

**Comment by ltguillaume** [comment]
While I understand the hesitation to add more features, I don't understand what good it would do to keep close to what the Google application does. Google's UX changes have been notoriously bad and almost every iteration of Material causes function and ergonomic ease to be traded in for stylishness. There is no reason whatsoever to stay close to whatever Google comes up with.

I don't see how "ugly" factors into this, as an alarm should be functional above all and there are endless possibilities to make a layout as proposed look fancy.

As for using my phone while in traffic, that's exactly why this feature would have great benefit. 

I go by bike most often, so my phone is in my pocket.

If I'm running late and the alarm goes off, I could either be annoyed by it for as long as it keeps ringing (and surely cause a terrible accident because of it!) or just dismiss the alarm easily, without ever taking my eyes off the road.

**Comment by BlackyHawky** [comment]
> I don't understand what good it would do to keep close to what the Google application does.

Simply because this application is based on [AOSP Deskclock](https://android.googlesource.com/platform/packages/apps/DeskClock/) provided by Google and when I took over this application this year, I always wanted to stay close to the initial interface.

The main goal of the changes is to have a Google-like app that is as privacy-friendly as possible (mostly without internet connection) for people who like Google interface.

I can understand that you don't like the Google interface but that's not the case for everyone and I know a lot of them.

Finally, if you don't want to take your phone out of your pocket to turn off the alarm, you can either use the volume buttons or the power button. Both can be configured in the Alarms settings.
