### ISSUE TITLE
Cannot dismiss upcoming alarm after updating to 2.10

### ISSUE THREAD

**Issue by xfzv** [BlackyHawky/Clock#136]
**Describe the bug**

I have a recurring alarm that repeats every day of the week. After updating to 2.10, tapping "Dismiss" on the Android notification just leads to said notification coming back over and over (the alarm isn't dismissed).

After disabling/enabling the alarm in the app, tapping "Dismiss" works. I have to do this the next day and so on.

Used to work just fine on previous versions.

**To Reproduce**

**Expected behavior**

Tapping "dismiss" dismisses the alarm

**Screenshots**

**App version**

2.10

**Device (please complete the following information):**
 - Model:  OnePlus 7 Pro
 - OS:  Android 15 / YAAP

**Additional context**

**Comment by dolphingod69** [comment]
I have exactly the same issue

**Comment by BlackyHawky** [comment]
This bug is confirmed; I realized it this week. Unfortunately, because of my real job, I can't find the time to find the reason.
This is my first priority, I will do what it takes to publish a new version as soon as possible.

**Comment by smjkh** [comment]
Yeah same here OP 12R, one alarm I could dismiss the notification but the alarm still rang, the other every time I hit dismiss the notification just came right back

**Comment by BlackyHawky** [comment]
Despite my limited free time, I was able to do a few tests.
This bug comes from the new feature added: _"Set an alarm on a specific date"_ (commit 00d6ef2).

I'm disappointed because this is a specific case that I hadn't tested before; moreover, I can't identify the exact source of the bug.

Tonight (Paris local time), I'll have more time to try and find the solution.

Please note: if I can't solve this problem quickly, I'll be forced to remove this new feature in order to provide users with a "clean" version until a solution is found.

**Comment by BlackyHawky** [comment]
I am really sorry but I did not find the reason for this bug.

So I prefer to remove the functionality to set an alarm on a specific date and provide a new version without this inconvenience.

I hope to find the solution soon.

**Comment by BlackyHawky** [comment]
@xfzv @smjkh @dolphingod69 @resiehnnes @dpi0 @BluePixel4k
(I hope I forgot anyone who reacted in this topic)

I released a new version without the _"Set an alarm on a specific date"_ feature. You can download it [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1).
Unfortunately, I couldn't find the source of this major bug. 😭

**Comment by BlackyHawky** [comment]
@mimaiself
It is better to discuss this problem here so as not to pollute the topic you opened.

**<ins>To everyone:</ins>**

To reproduce the bug:
1. Set the device date to Monday and set the device time to 10:15 AM.
2. Create a new alarm and set it for 10:16 PM.
3. Select the days Tuesday and Wednesday for this alarm
4. Quit the app by removing it from recently opened apps
5. Set the device date to Tuesday and set the device time to 10:15 PM.
6. Wait a few seconds and the alarm will trigger; when you dismiss it, the bug will appear.

The Android Studio log confirms the bug but despite this I still don't know which part of the code to modify...

Tested on Huawei phone with Android 12 and Samsung tablet with Android 14.

**Comment by aidaho** [comment]
> @xfzv @smjkh @dolphingod69 @resiehnnes @dpi0 @BluePixel4k (I hope I forgot anyone who reacted in this topic)
> 
> I released a new version without the _"Set an alarm on a specific date"_ feature. You can download it [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1). Unfortunately, I couldn't find the source of this major bug. 😭

Thank you for the update.  
My alarms suddenly stopped working two days ago and I've traced this down to Clock update.
Today 2.10.1 has successfully woken me up.

**Comment by resiehnnes** [comment]
Can confirm that 2.10.1 works smooth so far, while 2.10 had issues on Xiaomi 14 Ultra. @BlackyHawky thank you for your hard work!

**Comment by smjkh** [comment]
Thanks for being so attentive to this, appreciate the quick fix!

**Comment by BlackyHawky** [comment]
Thank you all for your encouragement ❤️

**Comment by ltguillaume** [comment]
Now this is the proper way to deal with issues caused by new features: provide a stable version first, then check if it can be fixed. Nextcloud devs could learn a lot from you, @BlackyHawky (https://github.com/nextcloud/android/issues/13872)
