### ISSUE TITLE
FR: Please have it look closer to Google clock

### ISSUE THREAD

**Issue by Raj2032** [BlackyHawky/Clock#14]
https://play.google.com/store/apps/details?id=com.google.android.deskclock

If you take a look at their screenshots:

<img width=200 src="https://user-images.githubusercontent.com/29293830/194020180-2dba0ba0-e75c-4bc0-aa6a-1e22dcf06d92.png">
<img width=200 src="https://user-images.githubusercontent.com/29293830/194020240-8a8c429c-a1a4-4e64-8fc3-fddb0805def4.png">

I was hoping we could have a setting to switch to this look UI?

**Comment by BlackyHawky** [comment]
For information: Due to the migration of the repository, commit [Vibrator not activated on alarm creation](https://github.com/BlackyHawky/Clock/commit/6d98bb01566de7c4af359a91d550e30d351479b4) has nothing to do with this subject.

Moreover, we can consider this subject closed following the recent changes made.
