### ISSUE TITLE
Differentiation between "alarm" and "wake-up alarm"

### ISSUE THREAD

**Issue by mimaiself** [BlackyHawky/Clock#149]
**Is your feature request related to a problem? Please describe.**
If no alarm is set in the app, the message "No alarms" appears on the alarm display. The same message is also displayed in bedtime mode if no alarm is set there. But an alarm and a wake-up alarm are two different actions!

**Describe the solution you'd like**
To make this clearer for users, it would be nice if the message "No wake-up alarm" were shown in the bedtime display. The alarm created in bedtime mode is already shown in the alarm display under the automatically generated and unchangeable title "Wake-up alarm".

**Comment by BlackyHawky** [comment]
@mimaiself 
As I indicated in another topic, I will not work on the bedtime mode because I am not the one who implemented it and above all I find it totally useless (there are also some bugs).

If it were up to me, I would remove it from the application.
Besides, this is perhaps what I will do in the near future where I will create a dedicated branch so that another person can use it as a base.

That is why I will leave it as is in order not to create useless strings which would increase the size of the application unnecessarily.

**Comment by mimaiself** [comment]
I can understand your thoughts. I don't like the bedtime mode either.
