### ISSUE TITLE
Is the Ignore Battery Optimizations permission really necessary?

### ISSUE THREAD

**Issue by brian6932** [BlackyHawky/Clock#31]
**Is your feature request related to a problem? Please describe.**

![](https://github.com/BlackyHawky/Clock/assets/18603393/5a82c8fc-53ca-42ab-9099-0699316cae98)
There are some permissions I don't want/have to grant in particular the Ignore Battery Optimizations permission.
Without granting this permission, the permission dialog is displayed every time the application is launched.

**Describe the solution you'd like**
Remove Ignore Battery Optimizations permission.

**Comment by BlackyHawky** [comment]
@brian6932 Can you please specify which permissions you don't want to grant?

As discussed in #27, this message only appears if essential permissions are not granted, and these guarantee correct alarm operation.
In the permissions management page, essential permissions are indicated by **_Highly recommended_** in the _Requirement_ field.

@qw123wh, @odmfl, @Nilsu11: As this is the 2nd issue on this subject, can I have your opinion on this topic ?

**Comment by brian6932** [comment]
I don't think that granting ignore battery optimizations is a necessary thing, may be on some devices, but for me the Google Clock app (AOSP based) works perfectly fine without it.

**Comment by BlackyHawky** [comment]
Is your Google Clock app a system application?

Moreover, I did a little test:
- I set an alarm;
- I forced the application to close, just as battery optimization would do;
- The alarm didn't trigger.

So I'm not sure whether this authorization should be removed.

**Comment by brian6932** [comment]
>Is your Google Clock app a system application?

No, battery optimization depends on the device, ROM, and Kernel.

**Comment by qw123wh** [comment]
Battery authorization is required on some devices, while on others it is not.

So it's right that it's there, because if removed there will be 1000 other problems that the alarm doesn't ring. 

The only thing that could be done is that if the permissions are not granted the warning does not appear again.

Then it's not that if you grant permission the app consumes the battery, the consumption is equal to 0. In fact this permission is also very useful in energy saving mode otherwise the alarm wouldn't sound. Even the lineage clock app itself does not appear to have authorization but if you go into the app settings you can't even deactivate the battery authorization.

**Comment by odmfl** [comment]
The only solution that comes to mind for me too is to stop the message from appearing if the user doesn't want to give permission, practically having the same behavior as for "non-essential" permissions. 

If the app does not work correctly, the user will give permissions manually.

**Comment by BlackyHawky** [comment]
@qw123wh: Thank you for the clarification.

Instead of the message, I will try to display a message which will only be present in the settings.
I'll keep you informed.

I closed this conversation which rather concerned the Ignore Battery Optimizations permission.
About the toast message, this will be covered in #27.
