### ISSUE TITLE
Timer functions have haptic feedback, override system settings

### ISSUE THREAD

**Issue by CaviaPorcellus** [BlackyHawky/Clock#33]
**Describe the bug**
I have all haptic/touch feedback turned off in Android's system settings. Certain functions of the clock app (namely the timer) causes haptic feedback despite this. No other apps I use (including the default Google Clock app) do this.

**To Reproduce**
1. Ensure that haptic/touch feedback is turned off in Android's System Settings. 
2. Open the Clock app and set a timer.
3. Feel the haptic feedback when setting the timer's time, starting it, pausing it, etc.

**Expected behavior**
The app should obey system settings and not have any haptic feedback. I do see a "Timer vibrate" setting in the app's settings, which is turned off (not sure what that setting does).

**App version**
Clock version 2.0 (installed from F-Droid)

**Device (please complete the following information):**
 - Model: Google Pixel 3
 - OS: Android 12

**Comment by BlackyHawky** [comment]
This is not a bug, as it was the expected behavior.
However, I agree that it's a possibility to add a parameter to activate or not the vibrations to the interface.

Is it ok for you? Personally, I don't have a problem with it, as it would give users more freedom to customize their interface.

> I do see a "Timer vibrate" setting in the app's settings, which is turned off (not sure what that setting does).

This allows you to use the device's vibrator when the alarm is triggered at the end of the timer.

**Comment by CaviaPorcellus** [comment]
I see, yes, an option would be fine. Though it seems odd to me that the default would be something that overrides Android's system-wide settings (which is why I thought it was a bug). Regardless, thanks for your work on the app.
