### ISSUE TITLE
FR: Bigger widget / customisation

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#37]
**Is your feature request related to a problem? Please describe.**
Widget clock is (relatively) small-ish

**Describe the solution you'd like**
Being able to extend it (currently it adds other configured timzones). 
Would also be nice to be able to customize font size (clock/date)

**Use case**
It's handy to have well visible clock (possibly matter of habit)

**Comment by BlackyHawky** [comment]
I'm guessing you're talking about the modern digital widget?

For the moment, this is the expected behavior of adding cities when extending the widget. The goal is to create a modern widget dedicated to cities only (like Google), but I'm not able to do that. 😬

Moreover, I'm sure I'll never work on this topic because I use the [Breezy Weather](https://github.com/breezy-weather/breezy-weather) widget unless LineageOS or crDroid updates.

> Being able to extend it...

Does that mean you can't extend it?

**Comment by woj-tek** [comment]
> I'm guessing you're talking about the modern digital widget?

yes :-)



> For the moment, this is the expected behavior of adding cities when extending the widget. The goal is to create a modern widget dedicated to cities only **(like Google)**, but I'm not able to do that. 😬

Hmmm, why it has to be "like google"?



> Does that mean you can't extend it?

I mean I can't resize it without adding cities :D I was expecting increasing size of the clock and surprise - cities popped up :D



> Moreover, I'm sure I'll never work on this topic because I use the [Breezy Weather](https://github.com/breezy-weather/breezy-weather) widget unless LineageOS or crDroid updates.

I use that app but hmm... Added clock widget from clock app as it made sense :-) Also - widget from app usually tend to open that app when taped so using "native app widget" made even more sense. Ages ago I was using dedicated clock widget which was highly customizable but it's development stopped at one point (and because of some api changes it stopped refreshing when in app causing jarring experience) thus I ended with previous incaration of this app and it's widget and everything was "working mostly fine" :-)

**Comment by BlackyHawky** [comment]
> Hmmm, why it has to be "like google"?

Because this application is very much inspired by the original google clock application but when I say "like Google", I don't mean "_necessarily_ like Google".

In any case, when I implemented the modern widgets, I had thought of removing the cities.
Maybe I can do it just for the modern digital widget. 🤔
To customize the widget, I believe there's a commit on LineageOS, but it requires a lot of work...

**Comment by woj-tek** [comment]
> Because this application is very much inspired by the original google clock application but when I say "like Google", I don't mean "_necessarily_ like Google".

But there is already [Google Clock](https://play.google.com/store/apps/details?id=com.google.android.deskclock) so if anyone wants to have "like google" then they can use clock from google directly? :-)



> In any case, when I implemented the modern widgets, I had thought of removing the cities.
> Maybe I can do it just for the modern digital widget. 🤔

I think that could work (if it also makes clock size-up trying to fill the space of the widget) :)

**Comment by qw123wh** [comment]
> > Because this application is very much inspired by the original google clock application but when I say "like Google", I don't mean "_necessarily_ like Google".
> 
> But there is already [Google Clock](https://play.google.com/store/apps/details?id=com.google.android.deskclock) so if anyone wants to have "like google" then they can use clock from google directly? :-)
> 
@woj-tek This app derives from the aosp clock (code released by google), and from improvements made by open source Custom Rom (Lineageos ect) this app wants to be the foss alternative to the google clock, it is normal that it is inspired by that. My intention when I created and released this app on fdroid was exactly that. At the time there were alternative open source Clock apps but none were complete and had functions like the aosp clock present in the custom roms. Today there are many alternative open-source clock apps, but I honestly don't feel like completely changing the nature of this app. If you want to change it, maybe it's better to change the app.

**Comment by woj-tek** [comment]
SOT:
@qw123wh Thanks for the explanation - understood.

I think my assumptions were just different and I was quite happy with the previous version (sans missing notification). On that note I think that I'm a person that doesn't necessarily chase after novelty (just for novelty; and keeping up with Google) nor is fond with Google re-designing the OS (just for the sake of re-design; and this is very subjective but MaterialYou is just very meh).

I spend a lot of time after cLock (from LineageOS) stopped being developed/published (don't remember what happened) looking for the replacement and found your clock and it was just the best. When I saw the updated the other day I though it was just a refresh to get up with the APIs, fix notifications and whatnot but in the end it was different app (previously you archived older version and made new one, I think it was somewhat more sensible/less surprising).

To that end, instead of trying to mould the new version I just downgraded to 1.2 - it works just fine, looks (IMHO) better, has simple widget. At one point I may take a look why the notification is not showing in fullscreen but given it doesn't show in 2.x version then there is no difference functional wise here :-)

Thank you for all your work (an all contributors) and sorry if I came across as harsh - this wasn't my intention :-(

**Comment by BlackyHawky** [comment]
> sorry if I came across as harsh

Don't worry, it's like car enthusiasts: many don't like modern cars and prefer older ones. It's the same with Android applications.
In any case, with the addition of settings in version 2.2, you should be able to get back (almost) the interface of version 1.2.

**Comment by MathewHDYT** [comment]
@BlackyHawky Amazing clock application and feature-wise one of the best open source ones there is by far.

I wanted to comment on this issue, because It seems it is the same option I was looking for.

Is it possible in the setting to change it so that the size of the shown time is increased because currently it is only ever 2 * 2 widget even if the given size is 4 * 4 or more (if there are no configured cities of course).

Would it be possible to add an option that allows the time to scale to the increased space meaning if it has no cities and is in a 4 * 4 widget window it would scale to fit that size?

---------

The best case would be if it were possible to switch between scaling the clock or showing the time of other cities. If it is already possible in the current UI I could sadly not find it :(.

**Comment by BlackyHawky** [comment]
@MathewHDYT:
Thanks for your comment. Despite my lack of experience, I try to produce useful and pleasant things for this application.

However, it's very difficult for me to handle all requests that's why I need a contributor.

BTW, which widget are we really talking about? The one with the transparent background?

@woj-tek : you've confirmed that this is the modern digital widget but by re-reading the code, I remembered that the cities display only appears in the application's initial widget: the one with a transparent background. Could you please clarify?

**Comment by MathewHDYT** [comment]
@BlackyHawky Yes exactly it is the one with the transparent backgtound but both the one without and with background fumction the same, meaning they do not scale with widget size and always stay at 2 * 2. (Additionally the transparent one shows cities, if they are configured.)

---------

From what I found perhaps the resize attribute on Widgets can help?

See official [Android Docs](https://developer.android.com/develop/ui/views/appwidgets#resizemode). This page also contains some more [info](https://developer.android.com/develop/ui/views/appwidgets/layouts#provide-exact-layouts).

**Comment by BlackyHawky** [comment]
@woj-tek, @MathewHDYT:
Can you test the apk below please?

Here are the main changes that affect only the transparent background widget:
- A toggle is added at the bottom of the settings to display cities or not;
- If the toggle is ON and at least one city is added to the Clock tab, the clock size is a little larger compared to before. (I will not increase the size any further so that it remains consistent with the size of the text about the cities);
- If the toggle is OFF, the size of the clock (and therefore the date and next alarm) **are much larger than before**.

Can you give me your opinion please?

[Clock_2.3-debug.zip](https://github.com/BlackyHawky/Clock/files/15416776/Clock_2.3-debug.zip)

**Comment by MathewHDYT** [comment]
@BlackyHawky Tested it. This is perfect, exactly what I wanted thanks a lot for the fast reply and implementation :D.

If the application can be officially released with these changes that would be amazing.

**Comment by BlackyHawky** [comment]
> @BlackyHawky Tested it. This is perfect, exactly what I wanted thanks a lot for the fast reply and implementation :D.
> 
> If the application can be officially released with these changes that would be amazing.

You're welcome. 😉

If @woj-tek's opinion is positive, this will indeed be part of the next release.
Moreover, the modern widget (the one with the background) will certainly have the same capability, but it will require a little more work.

**Comment by BlackyHawky** [comment]
@woj-tek, @MathewHDYT:
You can test the commit e3adef1 which adds the ability to change the font size of the digital widget clock in the settings.
As indicated in my previous comment, this is possible if no city is displayed.
For now, this is only possible with the transparent widget.

Could you please give me your opinion?

**Comment by MathewHDYT** [comment]
@BlackyHawky Would it be possible for you to create another Debug APK of the aforementioned changes. So I can test the changes more easily.

**Comment by woj-tek** [comment]
> you've confirmed that this is the modern digital widget but by re-reading the code, I remembered that the cities display only appears in the application's initial widget: the one with a transparent background. Could you please clarify?

Hmm... I don't remember there being more options - I remember there were analogue and digital one and I used the digital one for readability. And, as I said earlier, I reverted to v1.2 so it's somewhat difficult to check because the app-id is the same... 

Though I checked the attached debug version and it's great - clock is big and easily readable 💪

**Comment by BlackyHawky** [comment]
@woj-tek, @MathewHDYT, @qw123wh, @odmfl:

Can you test the apk below please?

I'd like to know if the transparent digital widget loads on your devices?
On the emulator, configured with API 23 or 28, it doesn't work and I have absolutely no idea why because I don't get any error message. Obviously, everything is fine on my devices.

In case it works on your devices, here's a summary of the additions I've made in the settings:
- Cities can be displayed or hidden;
- The color of the clock, date and city names can be changed;
- The font size of the main clock can be changed ;
- The font size of the main clock can be changed (only if no city is displayed because I want to keep the current font size when the cities are displayed so that everything is consistent);
- The alignment of the main clock can be modified (only if no city is displayed because I want to keep everything centered when cities are displayed);

Do you think the color of the city clocks should be independent of the color of the main clock?
The same goes for the color of the next alarm: should it have its own color?
Lastly, do you think the shadow of the main clock should be removed?

I am waiting for your feedback and thank you in advance.

[Clock_2.3-debug.zip](https://github.com/BlackyHawky/Clock/files/15437016/Clock_2.3-debug.zip)

**Comment by woj-tek** [comment]
> I'd like to know if the transparent digital widget loads on your devices?

It shows.

I tested below though I don't need any customisation apart from disabling world cities so I was very happy with previous build

> * Cities can be displayed or hidden;

✅ 

>     * The color of the clock, date and city names can be changed;

✅ 

>     * The font size of the main clock can be changed ;

✅ 

>     * The font size of the main clock can be changed (only if no city is displayed because I want to keep the current font size when the cities are displayed so that everything is consistent);

✅ 

>     * The alignment of the main clock can be modified (only if no city is displayed because I want to keep everything centered when cities are displayed);

✅ 

> Do you think the color of the city clocks should be independent of the color of the main clock? The same goes for the color of the next alarm: should it have its own color? Lastly, do you think the shadow of the main clock should be removed?

As said at the start - I don't need it at all :-)

EDIT: Actually I liked previous way it worked where the sizing was automatic based on the size of the widget - IMHO the most sensible way to adjust the font size.

**Comment by MathewHDYT** [comment]
@BlackyHawky I agree with @woj-tek it is probably the best way to simply do it like nearly all other widget do it. Which is to scale the text to the size the widget is given on the screen. So like it was with your previous APK.

For the color change it should probably be consistent between the city clocks and the big clock.
Additionally I think the shadow for the main clock should stay the same as well.

**Comment by odmfl** [comment]
@BlackyHawky for me it's fine, I find the possibility of increasing the font size of the widget good, the only thing if you could also add this possibility to the digital widget of the material you.

**Comment by BlackyHawky** [comment]
> EDIT: Actually I liked previous way it worked where the sizing was automatic based on the size of the widget - IMHO the most sensible way to adjust the font size.

I understand, but I've got to do what's necessary to make it work for as many people as possible.

Moreover, previously I had only indicated a value of `120` in the code.
If you do the same thing in the settings, you'll get the same behavior as before. Am I right?

We also need to think about large and small screens ; perhaps this 120 value isn't important enough or, on the contrary, is too high, which is why I'm giving the user the choice of adjusting it as he wishes.

> the only thing if you could also add this possibility to the digital widget of the material you.

It's planned 😉

---

Note: if the widget doesn't work on the emulator, it's because of the "Alignment" setting.

**Comment by MathewHDYT** [comment]
Makes sense, hanks a lot for your effort on implementing this feature :D. I'll eagearly await the final version.

**Comment by woj-tek** [comment]
> We also need to think about large and small screens ; perhaps this 120 value isn't important enough or, on the contrary, is too high, which is why I'm giving the user the choice of adjusting it as he wishes.

But if someone has big screen then they can simply make the widget smaller and the font size would be adjusted accordingly? I don't see particular use case where those two shouldn't go hand-in hand and be sized differently, i.e. making widget bigger but specifying smaller font size so that it would make... bigger margins?

**Comment by qw123wh** [comment]
@BlackyHawky I confirm as already said by @odmfl , for me too the size of the date is updated only in the "old digital widget". 

The material you widget grows but the date remains the same. 

If you install the debug app and have installed the 2.2 fdroid app, you will notice that even if you set a large size, the size of the date remains the same in the material you widget.

even the alignment option, whatever you choose, always seems the same to me


what is not related to this issue :on the initial page explaining permissions when the app is installed, the do not disturb permission is still mentioned which no longer exists.

**Comment by BlackyHawky** [comment]
@qw123wh:

As I said in my last comment, it's planned to apply these modifications to the material widget.

> what is not related to this issue :on the initial page explaining permissions when the app is installed, the do not disturb permission is still mentioned which no longer exists.

Thanks a lot! Corrected with commit 6c0702a.

---

@woj-tek:
By defining a fixed size in the code, if the user uses the widget in 2x2 and next to it chooses to put the widget of another application in 2x2, he won't be able to harmonize the font sizes of these 2 widgets.
This is a specific example, but it gives a reason why he can choose to define his own font size and not the one imposed by the developer.

**Comment by woj-tek** [comment]
> By defining a fixed size in the code, if the user uses the widget in 2x2 and next to it chooses to put the widget of another application in 2x2, he won't be able to harmonize the font sizes of these 2 widgets.
> This is a specific example, but it gives a reason why he can choose to define his own font size and not the one imposed by the developer.

I'm not using many widgets (basically this one and one from TodoAgenda) so experience is lacking. Maybe letting removing `dpi` so it would (always) be resized? (though setting it to 120 seems to work as before as you said)

**Comment by BlackyHawky** [comment]
> Maybe letting removing dpi so it would (always) be resized?

I don't understand what you mean?
Honestly, I don't think I'll change this setting unless many users complain about it.
Other applications have widgets where the font size can be customized; there's no reason why this shouldn't be the case for this application.

> (though setting it to 120 seems to work as before as you said)

Of course it works 😉

**Comment by BlackyHawky** [comment]
I think I've finished working on this. Can you please test the attached apk?

Details of the latest modifications:
- Removed the alignment setting as I find it ultimately useless;
- The color of all elements can be modified;
- Adjustments are made in a specific settings page;
- The digital widget can be configured with a long press on the widget for Android 9+;
- The material you widget can also be modified as promised;

[Clock_2.3-debug.zip](https://github.com/BlackyHawky/Clock/files/15447194/Clock_2.3-debug.zip)

**Comment by qw123wh** [comment]
> I think I've finished working on this. Can you please test the attached apk?
> 
> Details of the latest modifications:
> 
> * Removed the alignment setting as I find it ultimately useless;
> * The color of all elements can be modified;
> * Adjustments are made in a specific settings page;
> * The digital widget can be configured with a long press on the widget for Android 9+;
> * The material you widget can also be modified as promised;
> 
> [Clock_2.3-debug.zip](https://github.com/BlackyHawky/Clock/files/15447194/Clock_2.3-debug.zip)

Perfect for me 👍

**Comment by odmfl** [comment]
> I think I've finished working on this. Can you please test the attached apk?
> 
> Details of the latest modifications:
> 
> * Removed the alignment setting as I find it ultimately useless;
> * The color of all elements can be modified;
> * Adjustments are made in a specific settings page;
> * The digital widget can be configured with a long press on the widget for Android 9+;
> * The material you widget can also be modified as promised;
> 
> [Clock_2.3-debug.zip](https://github.com/BlackyHawky/Clock/files/15447194/Clock_2.3-debug.zip)

Yes,very good

**Comment by MathewHDYT** [comment]
Agreed with the others, I think it is perfect like this as well.

**Comment by BlackyHawky** [comment]
I am very happy to read your comments.
Perhaps other functions could/will be added, but in the meantime, it's more than enough to satisfy as many people as possible.

Thank you all for taking the time to test these modifications.

**Comment by MathewHDYT** [comment]
Thank you for the quick implementation of this feature and thanks for the nice application :D.

**Comment by woj-tek** [comment]
> I think I've finished working on this. Can you please test the attached apk?

A bit late to the party but the changes look awesome! Thanks a million! <3
