### ISSUE TITLE
Ability to ring to end of tune and no more

### ISSUE THREAD

**Issue by mildred** [BlackyHawky/Clock#40]
First thank you for this app with great features!

**Use case / Is your feature request related to a problem? Please describe.**

At some points during the day I like to have a reminder that it is this moment of the day by having a specific tune played (church bells). I want to listen it to the end and not dismiss nor have the alarm repeat.

Also, for morning wakeup I set another tune that I like to hear until the end, but here I still would like a repeat if I don't wake up.

**Describe the solution you'd like**

To the setting "stop ringtone after" add an option "at the end of the tune" and also make this global option configurable per alarm

To the setting "repeat duration" add the option "do not repeat" and also make this global option configurable per alarm.

**Use case**

See above

**Describe alternatives you've considered**

I configured the "stop ringtone after" to the approximate duration of the tune, and then I manually have to stop alarms I don't want to have repeated.

**Additional context**

I can't think of anything

**Comment by BlackyHawky** [comment]
@mildred 
Hi,

First of all, I apologize for my (very) late reply to your request. I hope you'll excuse me.

I've been working today on your request and will be finished soon.

However, your request about repeating alarms confuses me because I don't see the problem with this setting. 🤔

With my changes, you will be able to configure each alarm to stop when the ringtone ends. This means that it will not repeat itself. For others, they can be repeated as many times as defined in the "silence after" setting.

If you don't want an alarm to be snoozed, simply swipe the button on the right from the alarm animation that is triggered.

Is this the behavior you expect?

I suggest you test the attached apk and give me some feedback.

Thank you in advance.

[Clock_2.5-debug.zip](https://github.com/user-attachments/files/15854879/Clock_2.5-debug.zip)

**Comment by BlackyHawky** [comment]
@mildred 
After a few uses, I finally achieved everything you asked.
I believe I finally understood what you wanted with the repeating alarms. 😅

To summarize, here are the main changes:
- "The end of the ringtone" is added to the "Silence after" setting;
- "None" is added to the "Snooze length" setting;
- These 2 settings can be configured for each alarm in the expanded alarm view and for the Bedtime mode (Note: these two settings are only visible if they are not configured in the main settings to avoid unnecessary duplication);

- About the notifications:
  - If the user wants to listen to the ringtone until it ends and wants it to be repeated, the alarm will not be seen as missed but repeated until it is stopped manually;
  - If the user wants to listen to the ringtone until it ends and **doesn't** wants it to be repeated, the alarm will stop until the next instance without any notification;
  - Finally, as before, for all other values in these 2 settings, the alarm will be seen as missed and the notification will sound;

- About lock screen alarm activity:
  - If the user doesn't want the alarm to be repeated, the user will obviously not be able to snooze the alarm; he can only dismiss them. The icon and the text when the button is clicked have therefore been updated;


I provide you with a new debug version below if you want to test.
The changes will be merged this evening as we can consider this topic complete.

[Clock_2.5-debug.zip](https://github.com/user-attachments/files/15885922/Clock_2.5-debug.zip)
