### ISSUE TITLE
"Do nothing" action option  for Volume buttons just like it is for Power button, Flip and Shake conditions

### ISSUE THREAD

**Issue by Username1-a** [BlackyHawky/Clock#62]
**Additional context**
There is an action "Do nothing" for conditions like when Power button is pressed or device Flipped or Shaken in Alarms settings > Actions, but this action is missing for a condition when Volume buttons are pressed – it would make sense to add it to Volume buttons, too and would just make things a bit more consistent

**Comment by qw123wh** [comment]
what you ask for already exists for the volume keys too. The “do nothing” behavior in the volume keys is the same as “adjust volume” they have a different name but it is the same thing. “Do nothing” for the volume keys means that if I press the volume keys, the volume increases or decreases. As you can see, it's the same thing, furthermore the term "adjust volume" is more suitable.

**Comment by Username1-a** [comment]
@qw123wh Sorry for bringing this up again, but I keep accidentally lowering my alarm ringtone volume on wakeup with "Control Volume" (little by little it's lowering when you grab the phone etc, so you need to re-check if you accidentally silenced it completely)

Maybe it will be possible to alright block volume buttons input and add "Do Nothing" after all

Just a thought

**Comment by qw123wh** [comment]
@Username1-a If you press the volume buttons on your smartphone volume it goes up or down (normal android behavior), If you press the power button the screen turns off (normal android behavior). Flip and shake nothing happens (normal android behavior). The “do nothing” option simply performs the normal android behavior.

You could create a new issue that would be a feature request. The feature request you are asking is to add an option to inhibit the normal behavior of the volume buttons. I honestly don't know how to do it. But I repeat, for me it is to add an additional option, because as I repeat, "do nothing" for the volume buttons means raising or lowering the volume.

**Comment by BlackyHawky** [comment]
It bothered me that this inconvenience could occur and I think it needs to be resolved.
Indeed, it can happen to anyone who accidentally lowers the alarm volume using the device's volume buttons.

@Username1-a 
Could you test the apk attached and give me your opinion please?
I added a "Nothing" action to the "Volume button" setting and it works fine on my phone.

[Clock_2.6-debug.zip](https://github.com/user-attachments/files/17007079/Clock_2.6-debug.zip)

**Comment by Username1-a** [comment]
@BlackyHawky Thank you very much, tested it and it works flawlessly – alarm volume level no longer change when you accidentally press a button

Good luck to you

**Comment by BlackyHawky** [comment]
Great news!
I'm re-reading my changes and will publish a new version this week.
