### ISSUE TITLE
Alarms don't ring (most of the time?)

### ISSUE THREAD

**Issue by vymague** [BlackyHawky/Clock#71]
**Describe the bug**
I've set up a few recurring alarms in the morning.  
Sometimes a few of them triggered, sometimes none.  

**To Reproduce**
1. Set a new recurring alarm.

**Expected behavior**
The alarms to ring.

**App version**
Clock 2.5

**Device (please complete the following information):**
Multiple different devices. Not gonna say which. They are cheap older phones/Android if it matters.  
 - OS: Android 11 and 12

**Additional context**
I'm not even sure it's a bug from the program. As you know, Android has notification issues because of battery optimization, doze mode, and other nonsense. I've disabled those optimizations as much as I can. Also turned on the permissions requested by your app.  

For what it's worth, I feel this issue started since you started updating the app again. I used to think, the alarm didn't trigger because f-droid just installed a new version in the background. But doesn't look like it now.  

Great app though otherwise. It's crazy how other Android timers don't even have keypad interface or even sane multiple timers. Main reason I use your Clock. I can always use the default/buillt-in alarms to solve this issue.  

edit: Tried version 2.6 from f-droid and it doesn't even open lol.

**Comment by BlackyHawky** [comment]
@vymague 
Can you edit your topic specifying the device models + the android version for each please?
It is important to clearly indicate this because if other users have the same device(s), they will be able to tell us if they have the same bug.

In any case, I'm very surprised that you encountered this inconvenience.

I will not be able to reproduce it on my devices and without more information (logs) it will be impossible for me to know where it could come from.

A few questions though:
- When you stop a ringing alarm, does the next alarm appear correctly in the clock tab (or in the digital widget)?
- Did you encounter this bug in previous versions of the application?
- Does this bug appear when doing a new installation?

**Comment by morningnight0** [comment]
I also have this problem. Downloaded the app at version 2.5 and the alarm got ignored. Timer went off though.
Then I updated to 2.6 and the alarm got skipped again.
I set the alarm for a few hours because it was supposed to wake me up for work, but when I tried setting the alarm to ring right the next minute, it rang no problem.


I have a Redmi Note 13 with Android 14 and HyperOS.

**Comment by qw123wh** [comment]
@morningnight0 This is a problem with miui/hyperos, they are very restrictive systems.There are two solutions: 

1) deactivate the miui/hyperos optimizations in the developer options
2) go to the settings, in the installed apps and search for this app, click on it and give all the additional permissions required by miui/hyperos.

**Comment by BlackyHawky** [comment]
@morningnight0 
Can you tell me if this is the alarm created automatically when the application is installed, or an alarm you've created yourself?

**Comment by BlackyHawky** [comment]
@qw123wh 
Finally, it's more a problem that concerns the user's device rather than the application? 🤔

**Comment by vymague** [comment]
Just close this thread.  

Btw version 2.6 doesn't even open on my phones lol. Multiple brands, and different Android OS versions. I didn't record the error pop-up, and just uninstalled. I think it just so happens that I have cheap Chinese phones that are incompatible with your application. 

Good luck and thanks for the application.

**Comment by BlackyHawky** [comment]
@vymague 
Version 2.6 needs to be freshly installed for it to work. See [changelog](https://github.com/BlackyHawky/Clock/releases/tag/2.6).

**Comment by qw123wh** [comment]
> @qw123wh
> Finally, it's more a problem that concerns the user's device rather than the application? 🤔

Yes it is a problem of phones with very restrictive operating systems such as miui, hyperos, etc..
But there is always a solution, just deactivate all the "extra" restrictions present and it is solved. 
In any case it is not a problem with the app.
