### ISSUE TITLE
Application name under widget

### ISSUE THREAD

**Issue by klaseca** [BlackyHawky/Clock#83]
**Describe the bug**
Application name under widget

**To Reproduce**
1. Add widget to screen

**Expected behavior**
Just widget, without application name

**Screenshots**
![IMG_20240803_232417](https://github.com/user-attachments/assets/85ba3d2c-d8f9-4276-8a9b-304ce784166f)

**App version**
2.6

**Device (please complete the following information):**
 - Model: iQOO Neo9S Pro+
 - OS: Android 14 (OriginOS 4)

**Additional context**
If I use the "hide icon names" option in launcher, then application name disappears under widget. It seems that name should not be shown anyway

**Comment by BlackyHawky** [comment]
At first glance it's probably related to your app launcher because I use 3 different devices (Huawei, Samsung and Xiaomi) with 3 different Android versions and 4 different launchers and I've never encountered this bug.

Can you tell me if it's the same with widgets from other applications?

**Comment by klaseca** [comment]
Depends on widgets. Some have names, some don't. You may be right, because there are no problems when using Nova Launcher

<img width=200 src="https://github.com/user-attachments/assets/397cd23f-b4d4-449b-b479-f69e4d4e0bab">

**Comment by BlackyHawky** [comment]
Several images found on the net confirm that this bug is not linked to the application but to your device's launcher.

Indeed, we can see in these images that the application names appear below the widgets.

I invite you to change your launcher and continue to use Nova Launcher, which for me is the best in terms of customization.
