### ISSUE TITLE
Custom Accent Colour

### ISSUE THREAD

**Issue by D-Maxwell** [BlackyHawky/Clock#87]
Perhaps a colour picker could be displayed, or three channel sliders made available, or even but a bare hex field.

(it would also be nice having the option not to tint the background with the set accent colour, reserving it exclusively for upfront controls)

**Comment by BlackyHawky** [comment]
Aren't you happy with the current accent color customization?

Implementing the color picker is simple, since it already exists in the application.

However, to do what you're asking, it would require a lot of modifications; what I mean is that you'd have to define the color for each element that uses the "colorAccent" or "colorPrimary" attributes.

But maybe I can do something about the background color. I'll have to test it.

In any case, to be honest, at the moment, I don't want to waste time on this subject.
I'll leave it open until I do some tests, but maybe I'll close it.

**Comment by BlackyHawky** [comment]
2 months later I reread this topic and I won't do anything about it.

On the subject of themes, we already have sufficient settings, especially since the night mode colors have been improved with commit 86b6bfb.
