### ISSUE TITLE
Adding extra time longer than a minute

### ISSUE THREAD

**Issue by yephny** [BlackyHawky/Clock#9]
In timer, you can add extra time only minute by minute. Holding the +1 button should prompt a field where you can input an arbitrary number in minutes.

**Comment by BlackyHawky** [comment]
With the commit 6bf2a9d, the default time to add to the timer can be set in the timer settings.
However, we still can't choose a custom time.

**Comment by Maraxi** [comment]
Can we add more options on extension length? I see that adding a custom amount might be difficult.
But I think adding options for 15, 20 and 45 minutes might be useful since the current gaps between the options are quite large.
Another option would be to add an option that restarts the timer with its original run time, that would also solve my issue.

**Comment by BlackyHawky** [comment]
@Maraxi 
You can do this with a long press on the "add minutes" button. 😉
